version: '3.8'

services:
  sse-stub:
    image: rodolpheche/wiremock
    command: --verbose
    volumes:
      - ./wiremock:/home/wiremock

  proxy:
    image: local/issue-gatling-sse:${TAG}
    ports:
      - "8080:8080"